site_name: Orlando Rodriguez

plugins:
  - search
  - git-revision-date

theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - footer.prev_next
    - navigation.side.hide
    - revision.date

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects/index.md
  - Blog: blog/index.md

